
apiVersion: v1
kind: Service
metadata:
  name: api
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: api
spec:
  type: LoadBalancer
  ports:
  - port: 443
    protocol: TCP
  selector:
    api: api
